### ISSUE TITLE
Exporting DMs/Private Rooms

### ISSUE THREAD

**Issue by lhl** [gryf/slack-backup#3]
Hey, saw some other tools that do DM/Private room exports:

Go: https://github.com/joefitzgerald/slack-dump
Python 3: https://github.com/shikata-ga-nai/slack-dm-export/blob/master/im.py

Was looking to potentially integrate this functionality, but thought I'd start an issue to discuss before potentially doing a bunch of surgery to the Client class to see if you have any strong opinions on that (might also need to expand Objects, Reporter class, other bits...)

**Comment by gryf** [comment]
Yeah, I think that exporting direct messages/private rooms would be a plus for the functionality. I was looking at the api for such functionality like year ago, but didn't found any direct way for achieve that. If you could add such feature, it would be great :)
